export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SIGNOUT = 'SIGNOUT';

export const GET_PROFILE_POSTS_SUCCESS = 'GET_PROFILE_POSTS_SUCCESS';
export const GET_PROFILE_POSTS_ERROR = 'GET_PROFILE_POSTS_ERROR';

export const SAVE_PROFILE_POST_SUCCESS = 'SAVE_PROFILE_POST_SUCCESS';
export const SAVE_PROFILE_POST_ERROR = 'SAVE_PROFILE_POST_ERROR';

export const DELETE_PROFILE_POST_SUCCESS = 'DELETE_PROFILE_POST_SUCCESS';
export const DELETE_PROFILE_POST_ERROR = 'DELETE_PROFILE_POST_ERROR';

export const UPDATE_PROFILE_POST_SUCCESS = 'UPDATE_PROFILE_POST_SUCCESS';
export const UPDATE_PROFILE_POST_ERROR = 'UPDATE_PROFILE_POST_ERROR';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';